// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newMission6_hls68.Models;

namespace newMission6_hls68.Migrations
{
    [DbContext(typeof(DateApplicationContext))]
    [Migration("20230210214031_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("newMission6_hls68.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("movieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            movieId = 1,
                            category = "Anime",
                            director = " Hayao Miyazaki",
                            edited = false,
                            lentTo = "Hannah",
                            notes = "This is a classic!",
                            rating = "G",
                            title = "Kiki's Delivery Service",
                            year = 1989
                        },
                        new
                        {
                            movieId = 2,
                            category = "Anime",
                            director = " Hayao Miyazaki",
                            edited = false,
                            lentTo = "Daniel",
                            notes = "Love this movie!",
                            rating = "G",
                            title = "Ponyo",
                            year = 2008
                        },
                        new
                        {
                            movieId = 3,
                            category = "Disney",
                            director = "AAron Blaise",
                            edited = false,
                            lentTo = "Ben",
                            notes = "This is my favorite!",
                            rating = "PG",
                            title = "Brother Bear",
                            year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
